// Generated by watchDemo.mjs, DO NOT EDIT this file
import React from 'react';
import PageWalker from '@docs/components/PageWalker';

const requireDemo = import.meta.globEager('./*.tsx');

import basic from './basic.tsx?raw';
import computed from './computed.tsx?raw';
import pass from './pass.tsx?raw';
import list from './list.tsx?raw';
import remote from './remote.tsx?raw';
import message from './message.tsx?raw';

const requireRaw = {
  basic,
  computed,
  pass,
  list,
  remote,
  message,
};

import zh from './index-zh.md?raw';
import en from './index-en.md?raw';
const requireMd = { zh, en };

const Page: React.FC = () => {
  return <PageWalker requireDemo={requireDemo} requireRaw={requireRaw} requireMd={requireMd} />;
};
export default Page;
